spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DigitalCopyright?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    limit: 2
    limitTime: 10
    host: smtp.qq.com
    port: 465
    username: 847070349@qq.com
    password: cgmlggsnvctpbahf
    protocol: smtp
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
              port: 465
              fallback: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8888


logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework: DEBUG


webase:
  url: http://192.168.126.143:5002/WeBASE-Front/trans/handle


fisco:
  contract:
    address: "0xddc08e99560af0b2f0a3431d6c2c010ff1492d48"
    adminPrivateKey: dbd205db9627503e798e279eaecf4ca111ec82ca4f7e8acf8f13f986e1bccc3b


